Feature/form html exercise
EstefaSora125/html-tutorial pull request #4
Opened 2020-04-28 02:22 UTC by EstefaSora125

Exercise form by Estefania Sora

2020-04-29 02:05 UTC, pushdev-code requested changes
Just some small comments. If possible try to complete the exercise with your own elements. Mastery Is About How You Practice.

2020-04-29 02:05 UTC, pushdev-code commented on 4-forms-validations/form-html.html
> +         <label for="first-name">
```suggestion
         <label for="Lastname">
```

2020-04-29 02:05 UTC, pushdev-code commented on 4-forms-validations/form-html.html
> +        <label for="taste_2">Do origami</label>
```suggestion
        <input type="checkbox" id="taste_3" name="taste_origami" value="origami">
        <label for="taste_3">Do origami</label>
```

2020-04-29 02:05 UTC, pushdev-code commented on 4-forms-validations/form-html.html
> +          <button type="submit">Sumbit</button>
```suggestion
          <button>Submit</button>
```

2020-05-02 19:24 UTC, pushdev-code requested changes
It's not needed to use `aria-label="required"` in your `<abbr>` you can do: `<input aria-required="true" ....>` In all your inputs.

2020-05-02 19:24 UTC, pushdev-code commented on 4-forms-validations/form-html.html
> +            <select id="gender_user">
```suggestion
            <legend>Gender</legend>
            <label for="gender">Gender:</label>
            <select id="gender_user">
```

2020-05-06 23:09 UTC, juancho11gm approved these changes

2020-05-06 23:09 UTC, merged