Feature/estefania sora accessible form
EstefaSora125/html-tutorial pull request #5
Opened 2020-04-29 02:11 UTC by EstefaSora125

New accesible form project

2020-04-29 02:52 UTC, juancho11gm commented on 1-the-basics/index.html
> +</html>
This file is for the first exercise. Please remove it. Remember to create the new branch from `master` branch.

2020-04-29 03:06 UTC, juancho11gm commented on 5-Accessibility/accessible-form.html
> +                    <abbr title="required" aria-label="required">*</abbr>
nice to see the `aria-attributes`

2020-04-29 03:07 UTC, juancho11gm commented on 5-Accessibility/accessible-form.html
> +            <button type="submit">Send mesagge</button>
```suggestion
            <button>Send mesagge</button>
```

2020-04-29 03:08 UTC, juancho11gm requested changes
Nice job Estefanía! We are seeing your progress. Please see the comments and send the changes.

2020-05-02 19:12 UTC, pushdev-code approved these changes

2020-05-02 19:14 UTC, pushdev-code commented
Please resolve conflicting files in this PR. `1-the-basics/index.html` should not have any change.

2020-05-04 03:12 UTC, closed without merging

2020-05-04 03:13 UTC, EstefaSora125 commented
Change the project branch